// Autogenerated.  Takes 278 bytes of flash.

#ifndef _FACES_H
#define _FACES_H

#include "Animator.h"

extern const PROGMEM AnimationSequence eatFace_1;
extern const PROGMEM AnimationSequence eatFace_2;
extern const PROGMEM AnimationSequence eatFace_3;
extern const PROGMEM AnimationSequence eatFace_4;
extern const PROGMEM AnimationSequence satisfiedFace;
extern const PROGMEM AnimationSequence happyFace;

#endif