// Autogenerated.  Takes 546 bytes of flash.

#ifndef _FACES_H
#define _FACES_H

#include "Animator.h"

extern const PROGMEM AnimationSequence eatFace_1;
extern const PROGMEM AnimationSequence eatFace_2;
extern const PROGMEM AnimationSequence eatFace_3;
extern const PROGMEM AnimationSequence eatFace_4;
extern const PROGMEM AnimationSequence satisfiedFace;
extern const PROGMEM AnimationSequence happyFace;
extern const PROGMEM AnimationSequence asleepFace;
extern const PROGMEM AnimationSequence boredFace;
extern const PROGMEM AnimationSequence hungryFace;
extern const PROGMEM AnimationSequence neutralFace;
extern const PROGMEM AnimationSequence sickFace;
extern const PROGMEM AnimationSequence tiredFace;

#endif