// Autogenerated.  Takes 3,328 bytes of flash.
#ifndef _IMAGES_H
#define _IMAGES_H

extern const PROGMEM uint8_t attention[];
extern const PROGMEM uint8_t discipline[];
extern const PROGMEM uint8_t doctor[];
extern const PROGMEM uint8_t eat_1[];
extern const PROGMEM uint8_t eat_2[];
extern const PROGMEM uint8_t eat_3[];
extern const PROGMEM uint8_t eat_4[];
extern const PROGMEM uint8_t food[];
extern const PROGMEM uint8_t happy[];
extern const PROGMEM uint8_t info[];
extern const PROGMEM uint8_t light[];
extern const PROGMEM uint8_t play[];
extern const PROGMEM uint8_t satisfied[];
extern const PROGMEM uint8_t toilet[];

#endif