// Autogenerated.  Takes 246 bytes of flash.
// NOTE these are declared backwards for linked list purposes
#ifndef _SEQUENCES_H
#define _SEQUENCES_H

#include <avr/pgmspace.h>
#include "AnimationManager.h"
#include "images.h"
#include "globals.h"  // Face size declarations

#pragma region eatAnimation
static const PROGMEM AnimationElement _eatAnimation_frame_5_id2221356386816 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DEFAULT,
 .delay = 500,
 .image = satisfied,
 .next = nullptr
};

static const PROGMEM AnimationElement _eatAnimation_frame_4_id2221356386240 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DEFAULT,
 .delay = 350,
 .image = eat_4,
 .next = &_eatAnimation_frame_5_id2221356386816
};

static const PROGMEM AnimationElement _eatAnimation_frame_3_id2221356386624 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DEFAULT,
 .delay = 350,
 .image = eat_3,
 .next = &_eatAnimation_frame_4_id2221356386240
};

static const PROGMEM AnimationElement _eatAnimation_frame_4_id2221356386192 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DEFAULT,
 .delay = 350,
 .image = eat_4,
 .next = &_eatAnimation_frame_3_id2221356386624
};

static const PROGMEM AnimationElement _eatAnimation_frame_3_id2221356386432 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DEFAULT,
 .delay = 350,
 .image = eat_3,
 .next = &_eatAnimation_frame_4_id2221356386192
};

static const PROGMEM AnimationElement _eatAnimation_frame_4_id2221356385328 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DEFAULT,
 .delay = 350,
 .image = eat_4,
 .next = &_eatAnimation_frame_3_id2221356386432
};

static const PROGMEM AnimationElement _eatAnimation_frame_3_id2221356386336 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DEFAULT,
 .delay = 350,
 .image = eat_3,
 .next = &_eatAnimation_frame_4_id2221356385328
};

static const PROGMEM AnimationElement _eatAnimation_frame_4_id2221356385664 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DEFAULT,
 .delay = 350,
 .image = eat_4,
 .next = &_eatAnimation_frame_3_id2221356386336
};

static const PROGMEM AnimationElement _eatAnimation_frame_3_id2221356386144 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DEFAULT,
 .delay = 350,
 .image = eat_3,
 .next = &_eatAnimation_frame_4_id2221356385664
};

static const PROGMEM AnimationElement _eatAnimation_frame_2_id2221356385136 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DEFAULT,
 .delay = 400,
 .image = eat_2,
 .next = &_eatAnimation_frame_3_id2221356386144
};

static const PROGMEM AnimationElement _eatAnimation_frame_1_id2221356385856 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DEFAULT,
 .delay = 800,
 .image = eat_1,
 .next = &_eatAnimation_frame_2_id2221356385136
};

static const PROGMEM AnimationSequence eatAnimation = 
{
 .id = 0,
 .head = &_eatAnimation_frame_1_id2221356385856
};
#pragma endregion eatAnimation

#pragma region testAnimation
static const PROGMEM AnimationElement _testAnimation_frame_13_id2221356387776 = 
{
 .x = 96,
 .y = 0,
 .w = ICON_WIDTH,
 .h = ICON_HEIGHT,
 .meta = IMAGE_CLEARDISPLAY,
 .delay = 200,
 .image = attention,
 .next = nullptr
};

static const PROGMEM AnimationElement _testAnimation_frame_12_id2221356388160 = 
{
 .x = 88,
 .y = 8,
 .w = ICON_WIDTH,
 .h = ICON_HEIGHT,
 .meta = IMAGE_CLEARDISPLAY,
 .delay = 200,
 .image = attention,
 .next = &_testAnimation_frame_13_id2221356387776
};

static const PROGMEM AnimationElement _testAnimation_frame_11_id2221356387728 = 
{
 .x = 80,
 .y = 16,
 .w = ICON_WIDTH,
 .h = ICON_HEIGHT,
 .meta = IMAGE_CLEARDISPLAY,
 .delay = 200,
 .image = attention,
 .next = &_testAnimation_frame_12_id2221356388160
};

static const PROGMEM AnimationElement _testAnimation_frame_10_id2221356387968 = 
{
 .x = 72,
 .y = 24,
 .w = ICON_WIDTH,
 .h = ICON_HEIGHT,
 .meta = IMAGE_CLEARDISPLAY,
 .delay = 200,
 .image = attention,
 .next = &_testAnimation_frame_11_id2221356387728
};

static const PROGMEM AnimationElement _testAnimation_frame_9_id2221356386912 = 
{
 .x = 64,
 .y = 32,
 .w = ICON_WIDTH,
 .h = ICON_HEIGHT,
 .meta = IMAGE_CLEARDISPLAY,
 .delay = 200,
 .image = attention,
 .next = &_testAnimation_frame_10_id2221356387968
};

static const PROGMEM AnimationElement _testAnimation_frame_8_id2221356387872 = 
{
 .x = 56,
 .y = 40,
 .w = ICON_WIDTH,
 .h = ICON_HEIGHT,
 .meta = IMAGE_CLEARDISPLAY,
 .delay = 200,
 .image = attention,
 .next = &_testAnimation_frame_9_id2221356386912
};

static const PROGMEM AnimationElement _testAnimation_frame_7_id2221356387200 = 
{
 .x = 48,
 .y = 48,
 .w = ICON_WIDTH,
 .h = ICON_HEIGHT,
 .meta = IMAGE_CLEARDISPLAY,
 .delay = 200,
 .image = attention,
 .next = &_testAnimation_frame_8_id2221356387872
};

static const PROGMEM AnimationElement _testAnimation_frame_6_id2221356387680 = 
{
 .x = 40,
 .y = 40,
 .w = ICON_WIDTH,
 .h = ICON_HEIGHT,
 .meta = IMAGE_CLEARDISPLAY,
 .delay = 200,
 .image = attention,
 .next = &_testAnimation_frame_7_id2221356387200
};

static const PROGMEM AnimationElement _testAnimation_frame_5_id2221356386720 = 
{
 .x = 32,
 .y = 32,
 .w = ICON_WIDTH,
 .h = ICON_HEIGHT,
 .meta = IMAGE_CLEARDISPLAY,
 .delay = 200,
 .image = attention,
 .next = &_testAnimation_frame_6_id2221356387680
};

static const PROGMEM AnimationElement _testAnimation_frame_4_id2221356387392 = 
{
 .x = 24,
 .y = 24,
 .w = ICON_WIDTH,
 .h = ICON_HEIGHT,
 .meta = IMAGE_CLEARDISPLAY,
 .delay = 200,
 .image = attention,
 .next = &_testAnimation_frame_5_id2221356386720
};

static const PROGMEM AnimationElement _testAnimation_frame_3_id2221356387104 = 
{
 .x = 16,
 .y = 16,
 .w = ICON_WIDTH,
 .h = ICON_HEIGHT,
 .meta = IMAGE_CLEARDISPLAY,
 .delay = 200,
 .image = attention,
 .next = &_testAnimation_frame_4_id2221356387392
};

static const PROGMEM AnimationElement _testAnimation_frame_2_id2221356387296 = 
{
 .x = 8,
 .y = 8,
 .w = ICON_WIDTH,
 .h = ICON_HEIGHT,
 .meta = IMAGE_CLEARDISPLAY,
 .delay = 200,
 .image = attention,
 .next = &_testAnimation_frame_3_id2221356387104
};

static const PROGMEM AnimationElement _testAnimation_frame_1_id2221356386528 = 
{
 .x = 0,
 .y = 0,
 .w = ICON_WIDTH,
 .h = ICON_HEIGHT,
 .meta = IMAGE_CLEARDISPLAY,
 .delay = 200,
 .image = attention,
 .next = &_testAnimation_frame_2_id2221356387296
};

static const PROGMEM AnimationSequence testAnimation = 
{
 .id = 1,
 .head = &_testAnimation_frame_1_id2221356386528
};
#pragma endregion testAnimation

#endif