// Autogenerated.  Takes 246 bytes of flash.

#ifndef _SEQUENCES_H
#define _SEQUENCES_H

#include "Animator.h"

extern const PROGMEM AnimationSequence eatAnimation;
extern const PROGMEM AnimationSequence testAnimation;

#endif