// Autogenerated.  Takes 246 bytes of flash.
// NOTE these are declared backwards for linked list purposes

#include <avr/pgmspace.h>
#include "sequences.h"
#include "AnimationManager.h"
#include "images.h"
#include "globals.h"  // Face size declarations

#pragma region eatAnimation
static const PROGMEM AnimationElement _eatAnimation_frame_5_id2451936196304 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DEFAULT,
 .delay = 500,
 .image = satisfied,
 .next = nullptr
};

static const PROGMEM AnimationElement _eatAnimation_frame_4_id2451936197120 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DEFAULT,
 .delay = 350,
 .image = eat_4,
 .next = &_eatAnimation_frame_5_id2451936196304
};

static const PROGMEM AnimationElement _eatAnimation_frame_3_id2451936196640 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DEFAULT,
 .delay = 350,
 .image = eat_3,
 .next = &_eatAnimation_frame_4_id2451936197120
};

static const PROGMEM AnimationElement _eatAnimation_frame_4_id2451936196928 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DEFAULT,
 .delay = 350,
 .image = eat_4,
 .next = &_eatAnimation_frame_3_id2451936196640
};

static const PROGMEM AnimationElement _eatAnimation_frame_3_id2451936195200 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DEFAULT,
 .delay = 350,
 .image = eat_3,
 .next = &_eatAnimation_frame_4_id2451936196928
};

static const PROGMEM AnimationElement _eatAnimation_frame_4_id2451936196736 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DEFAULT,
 .delay = 350,
 .image = eat_4,
 .next = &_eatAnimation_frame_3_id2451936195200
};

static const PROGMEM AnimationElement _eatAnimation_frame_3_id2451936196256 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DEFAULT,
 .delay = 350,
 .image = eat_3,
 .next = &_eatAnimation_frame_4_id2451936196736
};

static const PROGMEM AnimationElement _eatAnimation_frame_4_id2451936196544 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DEFAULT,
 .delay = 350,
 .image = eat_4,
 .next = &_eatAnimation_frame_3_id2451936196256
};

static const PROGMEM AnimationElement _eatAnimation_frame_3_id2451936195056 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DEFAULT,
 .delay = 350,
 .image = eat_3,
 .next = &_eatAnimation_frame_4_id2451936196544
};

static const PROGMEM AnimationElement _eatAnimation_frame_2_id2451936196352 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DEFAULT,
 .delay = 400,
 .image = eat_2,
 .next = &_eatAnimation_frame_3_id2451936195056
};

static const PROGMEM AnimationElement _eatAnimation_frame_1_id2451936194864 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DEFAULT,
 .delay = 800,
 .image = eat_1,
 .next = &_eatAnimation_frame_2_id2451936196352
};

const PROGMEM AnimationSequence eatAnimation = 
{
 .id = 0,
 .head = &_eatAnimation_frame_1_id2451936194864
};
#pragma endregion eatAnimation

#pragma region testAnimation
static const PROGMEM AnimationElement _testAnimation_frame_13_id2451936198512 = 
{
 .x = 96,
 .y = 0,
 .w = ICON_WIDTH,
 .h = ICON_HEIGHT,
 .meta = IMAGE_CLEARDISPLAY,
 .delay = 200,
 .image = attention,
 .next = nullptr
};

static const PROGMEM AnimationElement _testAnimation_frame_12_id2451936198176 = 
{
 .x = 88,
 .y = 8,
 .w = ICON_WIDTH,
 .h = ICON_HEIGHT,
 .meta = IMAGE_CLEARDISPLAY,
 .delay = 200,
 .image = attention,
 .next = &_testAnimation_frame_13_id2451936198512
};

static const PROGMEM AnimationElement _testAnimation_frame_11_id2451936197984 = 
{
 .x = 80,
 .y = 16,
 .w = ICON_WIDTH,
 .h = ICON_HEIGHT,
 .meta = IMAGE_CLEARDISPLAY,
 .delay = 200,
 .image = attention,
 .next = &_testAnimation_frame_12_id2451936198176
};

static const PROGMEM AnimationElement _testAnimation_frame_10_id2451936198320 = 
{
 .x = 72,
 .y = 24,
 .w = ICON_WIDTH,
 .h = ICON_HEIGHT,
 .meta = IMAGE_CLEARDISPLAY,
 .delay = 200,
 .image = attention,
 .next = &_testAnimation_frame_11_id2451936197984
};

static const PROGMEM AnimationElement _testAnimation_frame_9_id2451936195104 = 
{
 .x = 64,
 .y = 32,
 .w = ICON_WIDTH,
 .h = ICON_HEIGHT,
 .meta = IMAGE_CLEARDISPLAY,
 .delay = 200,
 .image = attention,
 .next = &_testAnimation_frame_10_id2451936198320
};

static const PROGMEM AnimationElement _testAnimation_frame_8_id2451936197456 = 
{
 .x = 56,
 .y = 40,
 .w = ICON_WIDTH,
 .h = ICON_HEIGHT,
 .meta = IMAGE_CLEARDISPLAY,
 .delay = 200,
 .image = attention,
 .next = &_testAnimation_frame_9_id2451936195104
};

static const PROGMEM AnimationElement _testAnimation_frame_7_id2451936198080 = 
{
 .x = 48,
 .y = 48,
 .w = ICON_WIDTH,
 .h = ICON_HEIGHT,
 .meta = IMAGE_CLEARDISPLAY,
 .delay = 200,
 .image = attention,
 .next = &_testAnimation_frame_8_id2451936197456
};

static const PROGMEM AnimationElement _testAnimation_frame_6_id2451936197072 = 
{
 .x = 40,
 .y = 40,
 .w = ICON_WIDTH,
 .h = ICON_HEIGHT,
 .meta = IMAGE_CLEARDISPLAY,
 .delay = 200,
 .image = attention,
 .next = &_testAnimation_frame_7_id2451936198080
};

static const PROGMEM AnimationElement _testAnimation_frame_5_id2451936197888 = 
{
 .x = 32,
 .y = 32,
 .w = ICON_WIDTH,
 .h = ICON_HEIGHT,
 .meta = IMAGE_CLEARDISPLAY,
 .delay = 200,
 .image = attention,
 .next = &_testAnimation_frame_6_id2451936197072
};

static const PROGMEM AnimationElement _testAnimation_frame_4_id2451936197408 = 
{
 .x = 24,
 .y = 24,
 .w = ICON_WIDTH,
 .h = ICON_HEIGHT,
 .meta = IMAGE_CLEARDISPLAY,
 .delay = 200,
 .image = attention,
 .next = &_testAnimation_frame_5_id2451936197888
};

static const PROGMEM AnimationElement _testAnimation_frame_3_id2451936197696 = 
{
 .x = 16,
 .y = 16,
 .w = ICON_WIDTH,
 .h = ICON_HEIGHT,
 .meta = IMAGE_CLEARDISPLAY,
 .delay = 200,
 .image = attention,
 .next = &_testAnimation_frame_4_id2451936197408
};

static const PROGMEM AnimationElement _testAnimation_frame_2_id2451936196688 = 
{
 .x = 8,
 .y = 8,
 .w = ICON_WIDTH,
 .h = ICON_HEIGHT,
 .meta = IMAGE_CLEARDISPLAY,
 .delay = 200,
 .image = attention,
 .next = &_testAnimation_frame_3_id2451936197696
};

static const PROGMEM AnimationElement _testAnimation_frame_1_id2451936197504 = 
{
 .x = 0,
 .y = 0,
 .w = ICON_WIDTH,
 .h = ICON_HEIGHT,
 .meta = IMAGE_CLEARDISPLAY,
 .delay = 200,
 .image = attention,
 .next = &_testAnimation_frame_2_id2451936196688
};

const PROGMEM AnimationSequence testAnimation = 
{
 .id = 1,
 .head = &_testAnimation_frame_1_id2451936197504
};
#pragma endregion testAnimation

