// Autogenerated.  Takes 246 bytes of flash.
// NOTE these are declared backwards for linked list purposes

#include <avr/pgmspace.h>
#include "sequences.h"
#include "Animator.h"
#include "images.h"
#include "globals.h"  // Face size declarations

#pragma region eatAnimation
static const PROGMEM AnimationElement _eatAnimation_frame_5_id1470689662672 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DEFAULT,
 .delay = 500,
 .image = satisfied,
 .next = nullptr
};

static const PROGMEM AnimationElement _eatAnimation_frame_4_id1470689663488 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DEFAULT,
 .delay = 350,
 .image = eat_4,
 .next = &_eatAnimation_frame_5_id1470689662672
};

static const PROGMEM AnimationElement _eatAnimation_frame_3_id1470689663008 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DEFAULT,
 .delay = 350,
 .image = eat_3,
 .next = &_eatAnimation_frame_4_id1470689663488
};

static const PROGMEM AnimationElement _eatAnimation_frame_4_id1470689663296 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DEFAULT,
 .delay = 350,
 .image = eat_4,
 .next = &_eatAnimation_frame_3_id1470689663008
};

static const PROGMEM AnimationElement _eatAnimation_frame_3_id1470689661568 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DEFAULT,
 .delay = 350,
 .image = eat_3,
 .next = &_eatAnimation_frame_4_id1470689663296
};

static const PROGMEM AnimationElement _eatAnimation_frame_4_id1470689663104 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DEFAULT,
 .delay = 350,
 .image = eat_4,
 .next = &_eatAnimation_frame_3_id1470689661568
};

static const PROGMEM AnimationElement _eatAnimation_frame_3_id1470689662624 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DEFAULT,
 .delay = 350,
 .image = eat_3,
 .next = &_eatAnimation_frame_4_id1470689663104
};

static const PROGMEM AnimationElement _eatAnimation_frame_4_id1470689662912 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DEFAULT,
 .delay = 350,
 .image = eat_4,
 .next = &_eatAnimation_frame_3_id1470689662624
};

static const PROGMEM AnimationElement _eatAnimation_frame_3_id1470689661424 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DEFAULT,
 .delay = 350,
 .image = eat_3,
 .next = &_eatAnimation_frame_4_id1470689662912
};

static const PROGMEM AnimationElement _eatAnimation_frame_2_id1470689662720 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DEFAULT,
 .delay = 400,
 .image = eat_2,
 .next = &_eatAnimation_frame_3_id1470689661424
};

static const PROGMEM AnimationElement _eatAnimation_frame_1_id1470689661232 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DEFAULT,
 .delay = 800,
 .image = eat_1,
 .next = &_eatAnimation_frame_2_id1470689662720
};

const PROGMEM AnimationSequence eatAnimation = 
{
 .id = 0,
 .head = &_eatAnimation_frame_1_id1470689661232
};
#pragma endregion eatAnimation

#pragma region testAnimation
static const PROGMEM AnimationElement _testAnimation_frame_13_id1470689664880 = 
{
 .x = 96,
 .y = 0,
 .w = ICON_WIDTH,
 .h = ICON_HEIGHT,
 .meta = IMAGE_CLEARDISPLAY,
 .delay = 200,
 .image = attention,
 .next = nullptr
};

static const PROGMEM AnimationElement _testAnimation_frame_12_id1470689664544 = 
{
 .x = 88,
 .y = 8,
 .w = ICON_WIDTH,
 .h = ICON_HEIGHT,
 .meta = IMAGE_CLEARDISPLAY,
 .delay = 200,
 .image = attention,
 .next = &_testAnimation_frame_13_id1470689664880
};

static const PROGMEM AnimationElement _testAnimation_frame_11_id1470689664352 = 
{
 .x = 80,
 .y = 16,
 .w = ICON_WIDTH,
 .h = ICON_HEIGHT,
 .meta = IMAGE_CLEARDISPLAY,
 .delay = 200,
 .image = attention,
 .next = &_testAnimation_frame_12_id1470689664544
};

static const PROGMEM AnimationElement _testAnimation_frame_10_id1470689664688 = 
{
 .x = 72,
 .y = 24,
 .w = ICON_WIDTH,
 .h = ICON_HEIGHT,
 .meta = IMAGE_CLEARDISPLAY,
 .delay = 200,
 .image = attention,
 .next = &_testAnimation_frame_11_id1470689664352
};

static const PROGMEM AnimationElement _testAnimation_frame_9_id1470689661472 = 
{
 .x = 64,
 .y = 32,
 .w = ICON_WIDTH,
 .h = ICON_HEIGHT,
 .meta = IMAGE_CLEARDISPLAY,
 .delay = 200,
 .image = attention,
 .next = &_testAnimation_frame_10_id1470689664688
};

static const PROGMEM AnimationElement _testAnimation_frame_8_id1470689663824 = 
{
 .x = 56,
 .y = 40,
 .w = ICON_WIDTH,
 .h = ICON_HEIGHT,
 .meta = IMAGE_CLEARDISPLAY,
 .delay = 200,
 .image = attention,
 .next = &_testAnimation_frame_9_id1470689661472
};

static const PROGMEM AnimationElement _testAnimation_frame_7_id1470689664448 = 
{
 .x = 48,
 .y = 48,
 .w = ICON_WIDTH,
 .h = ICON_HEIGHT,
 .meta = IMAGE_CLEARDISPLAY,
 .delay = 200,
 .image = attention,
 .next = &_testAnimation_frame_8_id1470689663824
};

static const PROGMEM AnimationElement _testAnimation_frame_6_id1470689663440 = 
{
 .x = 40,
 .y = 40,
 .w = ICON_WIDTH,
 .h = ICON_HEIGHT,
 .meta = IMAGE_CLEARDISPLAY,
 .delay = 200,
 .image = attention,
 .next = &_testAnimation_frame_7_id1470689664448
};

static const PROGMEM AnimationElement _testAnimation_frame_5_id1470689664256 = 
{
 .x = 32,
 .y = 32,
 .w = ICON_WIDTH,
 .h = ICON_HEIGHT,
 .meta = IMAGE_CLEARDISPLAY,
 .delay = 200,
 .image = attention,
 .next = &_testAnimation_frame_6_id1470689663440
};

static const PROGMEM AnimationElement _testAnimation_frame_4_id1470689663776 = 
{
 .x = 24,
 .y = 24,
 .w = ICON_WIDTH,
 .h = ICON_HEIGHT,
 .meta = IMAGE_CLEARDISPLAY,
 .delay = 200,
 .image = attention,
 .next = &_testAnimation_frame_5_id1470689664256
};

static const PROGMEM AnimationElement _testAnimation_frame_3_id1470689664064 = 
{
 .x = 16,
 .y = 16,
 .w = ICON_WIDTH,
 .h = ICON_HEIGHT,
 .meta = IMAGE_CLEARDISPLAY,
 .delay = 200,
 .image = attention,
 .next = &_testAnimation_frame_4_id1470689663776
};

static const PROGMEM AnimationElement _testAnimation_frame_2_id1470689663056 = 
{
 .x = 8,
 .y = 8,
 .w = ICON_WIDTH,
 .h = ICON_HEIGHT,
 .meta = IMAGE_CLEARDISPLAY,
 .delay = 200,
 .image = attention,
 .next = &_testAnimation_frame_3_id1470689664064
};

static const PROGMEM AnimationElement _testAnimation_frame_1_id1470689663872 = 
{
 .x = 0,
 .y = 0,
 .w = ICON_WIDTH,
 .h = ICON_HEIGHT,
 .meta = IMAGE_CLEARDISPLAY,
 .delay = 200,
 .image = attention,
 .next = &_testAnimation_frame_2_id1470689663056
};

const PROGMEM AnimationSequence testAnimation = 
{
 .id = 1,
 .head = &_testAnimation_frame_1_id1470689663872
};
#pragma endregion testAnimation

