// Autogenerated.  Takes 246 bytes of flash.
// NOTE these are declared backwards for linked list purposes

#include <avr/pgmspace.h>
#include "sequences.h"
#include "Animator.h"
#include "images.h"
#include "globals.h"  // Face size declarations

#pragma region eatAnimation
static const PROGMEM AnimationElement _eatAnimation_frame_5_id2188455724752 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DEFAULT,
 .delay = 500,
 .image = satisfied,
 .next = nullptr
};

static const PROGMEM AnimationElement _eatAnimation_frame_4_id2188455725568 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DEFAULT,
 .delay = 350,
 .image = eat_4,
 .next = &_eatAnimation_frame_5_id2188455724752
};

static const PROGMEM AnimationElement _eatAnimation_frame_3_id2188455725088 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DEFAULT,
 .delay = 350,
 .image = eat_3,
 .next = &_eatAnimation_frame_4_id2188455725568
};

static const PROGMEM AnimationElement _eatAnimation_frame_4_id2188455725376 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DEFAULT,
 .delay = 350,
 .image = eat_4,
 .next = &_eatAnimation_frame_3_id2188455725088
};

static const PROGMEM AnimationElement _eatAnimation_frame_3_id2188455723648 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DEFAULT,
 .delay = 350,
 .image = eat_3,
 .next = &_eatAnimation_frame_4_id2188455725376
};

static const PROGMEM AnimationElement _eatAnimation_frame_4_id2188455725184 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DEFAULT,
 .delay = 350,
 .image = eat_4,
 .next = &_eatAnimation_frame_3_id2188455723648
};

static const PROGMEM AnimationElement _eatAnimation_frame_3_id2188455724704 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DEFAULT,
 .delay = 350,
 .image = eat_3,
 .next = &_eatAnimation_frame_4_id2188455725184
};

static const PROGMEM AnimationElement _eatAnimation_frame_4_id2188455724992 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DEFAULT,
 .delay = 350,
 .image = eat_4,
 .next = &_eatAnimation_frame_3_id2188455724704
};

static const PROGMEM AnimationElement _eatAnimation_frame_3_id2188455723504 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DEFAULT,
 .delay = 350,
 .image = eat_3,
 .next = &_eatAnimation_frame_4_id2188455724992
};

static const PROGMEM AnimationElement _eatAnimation_frame_2_id2188455724800 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DEFAULT,
 .delay = 400,
 .image = eat_2,
 .next = &_eatAnimation_frame_3_id2188455723504
};

static const PROGMEM AnimationElement _eatAnimation_frame_1_id2188455723312 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DEFAULT,
 .delay = 800,
 .image = eat_1,
 .next = &_eatAnimation_frame_2_id2188455724800
};

const PROGMEM AnimationSequence eatAnimation = 
{
 .id = 0,
 .head = &_eatAnimation_frame_1_id2188455723312
};
#pragma endregion eatAnimation

#pragma region testAnimation
static const PROGMEM AnimationElement _testAnimation_frame_13_id2188455726960 = 
{
 .x = 96,
 .y = 0,
 .w = ICON_WIDTH,
 .h = ICON_HEIGHT,
 .meta = IMAGE_CLEARDISPLAY,
 .delay = 200,
 .image = attention,
 .next = nullptr
};

static const PROGMEM AnimationElement _testAnimation_frame_12_id2188455726624 = 
{
 .x = 88,
 .y = 8,
 .w = ICON_WIDTH,
 .h = ICON_HEIGHT,
 .meta = IMAGE_CLEARDISPLAY,
 .delay = 200,
 .image = attention,
 .next = &_testAnimation_frame_13_id2188455726960
};

static const PROGMEM AnimationElement _testAnimation_frame_11_id2188455726432 = 
{
 .x = 80,
 .y = 16,
 .w = ICON_WIDTH,
 .h = ICON_HEIGHT,
 .meta = IMAGE_CLEARDISPLAY,
 .delay = 200,
 .image = attention,
 .next = &_testAnimation_frame_12_id2188455726624
};

static const PROGMEM AnimationElement _testAnimation_frame_10_id2188455726768 = 
{
 .x = 72,
 .y = 24,
 .w = ICON_WIDTH,
 .h = ICON_HEIGHT,
 .meta = IMAGE_CLEARDISPLAY,
 .delay = 200,
 .image = attention,
 .next = &_testAnimation_frame_11_id2188455726432
};

static const PROGMEM AnimationElement _testAnimation_frame_9_id2188455723552 = 
{
 .x = 64,
 .y = 32,
 .w = ICON_WIDTH,
 .h = ICON_HEIGHT,
 .meta = IMAGE_CLEARDISPLAY,
 .delay = 200,
 .image = attention,
 .next = &_testAnimation_frame_10_id2188455726768
};

static const PROGMEM AnimationElement _testAnimation_frame_8_id2188455725904 = 
{
 .x = 56,
 .y = 40,
 .w = ICON_WIDTH,
 .h = ICON_HEIGHT,
 .meta = IMAGE_CLEARDISPLAY,
 .delay = 200,
 .image = attention,
 .next = &_testAnimation_frame_9_id2188455723552
};

static const PROGMEM AnimationElement _testAnimation_frame_7_id2188455726528 = 
{
 .x = 48,
 .y = 48,
 .w = ICON_WIDTH,
 .h = ICON_HEIGHT,
 .meta = IMAGE_CLEARDISPLAY,
 .delay = 200,
 .image = attention,
 .next = &_testAnimation_frame_8_id2188455725904
};

static const PROGMEM AnimationElement _testAnimation_frame_6_id2188455725520 = 
{
 .x = 40,
 .y = 40,
 .w = ICON_WIDTH,
 .h = ICON_HEIGHT,
 .meta = IMAGE_CLEARDISPLAY,
 .delay = 200,
 .image = attention,
 .next = &_testAnimation_frame_7_id2188455726528
};

static const PROGMEM AnimationElement _testAnimation_frame_5_id2188455726336 = 
{
 .x = 32,
 .y = 32,
 .w = ICON_WIDTH,
 .h = ICON_HEIGHT,
 .meta = IMAGE_CLEARDISPLAY,
 .delay = 200,
 .image = attention,
 .next = &_testAnimation_frame_6_id2188455725520
};

static const PROGMEM AnimationElement _testAnimation_frame_4_id2188455725856 = 
{
 .x = 24,
 .y = 24,
 .w = ICON_WIDTH,
 .h = ICON_HEIGHT,
 .meta = IMAGE_CLEARDISPLAY,
 .delay = 200,
 .image = attention,
 .next = &_testAnimation_frame_5_id2188455726336
};

static const PROGMEM AnimationElement _testAnimation_frame_3_id2188455726144 = 
{
 .x = 16,
 .y = 16,
 .w = ICON_WIDTH,
 .h = ICON_HEIGHT,
 .meta = IMAGE_CLEARDISPLAY,
 .delay = 200,
 .image = attention,
 .next = &_testAnimation_frame_4_id2188455725856
};

static const PROGMEM AnimationElement _testAnimation_frame_2_id2188455725136 = 
{
 .x = 8,
 .y = 8,
 .w = ICON_WIDTH,
 .h = ICON_HEIGHT,
 .meta = IMAGE_CLEARDISPLAY,
 .delay = 200,
 .image = attention,
 .next = &_testAnimation_frame_3_id2188455726144
};

static const PROGMEM AnimationElement _testAnimation_frame_1_id2188455725952 = 
{
 .x = 0,
 .y = 0,
 .w = ICON_WIDTH,
 .h = ICON_HEIGHT,
 .meta = IMAGE_CLEARDISPLAY,
 .delay = 200,
 .image = attention,
 .next = &_testAnimation_frame_2_id2188455725136
};

const PROGMEM AnimationSequence testAnimation = 
{
 .id = 1,
 .head = &_testAnimation_frame_1_id2188455725952
};
#pragma endregion testAnimation

